FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o ingestor cmd/ingestor/main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/ingestor .
CMD ["./ingestor"]