FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o processor cmd/processor/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/processor .

CMD ["./processor"]