package config

type ConfigKey string

const (
	CFG_MYSQL_ROOT_PASSWORD = "MYSQL_ROOT_PASSWORD"
	CFG_MYSQL_DATABASE      = "MYSQL_DATABASE"
	CFG_MYSQL_USER          = "MYSQL_USER"
	CFG_MYSQL_PASSWORD      = "MYSQL_PASSWORD"
	CFG_MYSQL_PORT          = "MYSQL_PORT"

	CFG_MONGO_URI      = "MONGO_URI"
	CFG_MONGO_DATABASE = "MONGO_DATABASE"
	CFG_MONGO_USERNAME = "MONGO_USERNAME"
	CFG_MONGO_PASSWORD = "MONGO_PASSWORD"

	CFG_REDIS_PORT = "REDIS_PORT"
	CFG_REDIS_HOST = "REDIS_HOST"
)
